name: Kodi via Zip

on:
  push:
    branches:
      - '**'
      - '!kodi-leia'
      - '!kodi-matrix'

  pull_request:
    branches:
      - master

jobs:
  check-addon:
    name: Kodi Krypton/Leia ZIP Install Check (Py2)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kodi-branch: [krypton, leia]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # sudo apt-get install libxml2-utils
          python -m pip install --upgrade pip
          pip install kodi-addon-checker
      - name: Run kodi-addon-checker
        run: |
          kodi-addon-checker --branch=${{ matrix.kodi-branch }} .
